/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AddField: typeof import('./../../src/components/custom-form/addField.vue')['default']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    Button: typeof import('./../../src/components/button/index.vue')['default']
    DefaultOptions: typeof import('./../../src/components/custom-form/components/defaultOptions.vue')['default']
    DeptSelect: typeof import('./../../src/components/custom-form/components/deptSelect.vue')['default']
    EmailInput: typeof import('./../../src/components/custom-form/components/emailInput.vue')['default']
    FileUpload: typeof import('./../../src/components/custom-form/components/fileUpload.vue')['default']
    FormDesign: typeof import('./../../src/components/custom-form/formDesign.vue')['default']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconEmail: typeof import('@arco-design/web-vue/es/icon')['IconEmail']
    IconPhone: typeof import('@arco-design/web-vue/es/icon')['IconPhone']
    PhoneInput: typeof import('./../../src/components/custom-form/components/phoneInput.vue')['default']
    Render: typeof import('./../../src/components/custom-form/render/index.vue')['default']
    TreeOptions: typeof import('./../../src/components/custom-form/components/treeOptions.vue')['default']
  }
}
