/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    Button: typeof import('./../../src/components/button/index.vue')['default']
    IconPlus: typeof import('@arco-design/web-vue/es/icon')['IconPlus']
  }
}
